[project]
name = "gs-gmlip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ase>=3.26.0",
    "black>=25.9.0",
    "isort>=6.0.1",
    "jax>=0.7.2",
    "mace-torch>=0.3.14",
    "pandas>=2.3.3",
    "plumed>=2.10.0",
    "pytest>=8.4.2",
    "ruff>=0.13.1",
    "sphinx>=8.2.3",
]

[tool.black]
line-length = 88
target-version = ["py312"]

[tool.isort]
profile = "black"
line-length = 88

[tool.ruff]
line-length = 88
select = ["E", "F", "W"]
ignore = ["E501"]
