"""PLUMED interface for metadynamics with ASE.

Generates PLUMED input files and wraps the ASE Plumed calculator
for biased molecular dynamics.
"""

from __future__ import annotations

import logging
import tempfile
from pathlib import Path

import numpy as np
from ase import Atoms, units

from gs_gmlip.search.metadynamics.collective_vars import CollectiveVariable

logger = logging.getLogger(__name__)


def generate_plumed_input(
    cvs: list[CollectiveVariable],
    height: float = 0.1,
    sigma: list[float] | None = None,
    pace: int = 500,
    temperature: float = 300.0,
    biasfactor: float | None = None,
    file_prefix: str = "metad",
) -> str:
    """Generate PLUMED input string for metadynamics.

    Parameters
    ----------
    cvs : list of CollectiveVariable
        Collective variables.
    height : float
        Gaussian height (kJ/mol in PLUMED units).
    sigma : list of float, optional
        Gaussian widths per CV. If None, defaults to 0.1 for each.
    pace : int
        Steps between Gaussian depositions.
    temperature : float
        Temperature (K).
    biasfactor : float, optional
        If set, use well-tempered metadynamics.
    file_prefix : str
        Prefix for output files.

    Returns
    -------
    plumed_input : str
    """
    lines = [
        "# PLUMED input generated by gs_gmlip",
        "UNITS LENGTH=A ENERGY=eV TIME=fs",
        "",
    ]

    # CV definitions
    for cv in cvs:
        lines.append(cv.to_plumed_string())
    lines.append("")

    # Metadynamics
    cv_labels = ",".join(cv.label for cv in cvs)
    if sigma is None:
        sigma = [0.1] * len(cvs)
    sigma_str = ",".join(f"{s:.4f}" for s in sigma)

    metad_line = (
        f"metad: METAD ARG={cv_labels} "
        f"SIGMA={sigma_str} HEIGHT={height} PACE={pace} "
        f"FILE={file_prefix}_HILLS"
    )
    if biasfactor is not None:
        metad_line += f" BIASFACTOR={biasfactor} TEMP={temperature}"
    lines.append(metad_line)
    lines.append("")

    # Print CVs
    lines.append(
        f"PRINT ARG={cv_labels},metad.bias STRIDE={pace} FILE={file_prefix}_COLVAR"
    )

    return "\n".join(lines)


class PlumedCalculator:
    """Wrapper that creates an ASE Plumed calculator.

    Parameters
    ----------
    base_calc : Calculator
        The ASE calculator to wrap (e.g., MACE).
    plumed_input : str
        PLUMED input string.
    timestep : float
        MD timestep in fs.
    work_dir : str or Path
        Working directory for PLUMED files.
    """

    def __init__(
        self,
        base_calc,
        plumed_input: str,
        timestep: float = 1.0,
        work_dir: str | Path = ".",
    ):
        self.base_calc = base_calc
        self.plumed_input = plumed_input
        self.timestep = timestep
        self.work_dir = Path(work_dir)
        self._plumed_calc = None

    def get_calculator(self, atoms: Atoms):
        """Build and return the ASE Plumed calculator.

        Returns
        -------
        calc : ase.calculators.plumed.Plumed
        """
        try:
            from ase.calculators.plumed import Plumed
        except ImportError:
            raise ImportError(
                "ASE Plumed calculator not available. "
                "Install with: pip install gs_gmlip[plumed]"
            )

        self.work_dir.mkdir(parents=True, exist_ok=True)

        # Write PLUMED input file
        plumed_file = self.work_dir / "plumed.dat"
        plumed_file.write_text(self.plumed_input)

        # Create Plumed calculator
        self._plumed_calc = Plumed(
            calc=self.base_calc,
            input=self.plumed_input.split("\n"),
            timestep=self.timestep * units.fs,
            atoms=atoms,
            kT=units.kB * 300.0,  # Will be overridden in MD
        )

        return self._plumed_calc


def extract_minima_from_fes(
    hills_file: str | Path,
    cvs: list[CollectiveVariable],
    n_bins: int = 100,
    n_minima: int = 10,
) -> list[dict]:
    """Estimate FES from HILLS file and find minima.

    This is a simplified FES reconstruction. For production use,
    consider using plumed sum_hills utility.

    Parameters
    ----------
    hills_file : str or Path
        Path to the HILLS file.
    cvs : list of CollectiveVariable
        CV definitions.
    n_bins : int
        Number of bins per CV dimension.
    n_minima : int
        Maximum number of minima to return.

    Returns
    -------
    minima : list of dict
        Each dict has 'cv_values' and 'energy'.
    """
    hills_file = Path(hills_file)
    if not hills_file.exists():
        return []

    data = np.loadtxt(hills_file, comments="#")
    if data.ndim == 1:
        data = data.reshape(1, -1)

    n_cv = len(cvs)
    # Columns: time, cv1, cv2, ..., sigma1, sigma2, ..., height, biasfactor(optional)
    cv_data = data[:, 1 : 1 + n_cv]

    # Simple grid-based FES estimate
    minima = []
    if n_cv == 1:
        cv_min, cv_max = cv_data[:, 0].min(), cv_data[:, 0].max()
        grid = np.linspace(cv_min, cv_max, n_bins)
        fes = np.zeros(n_bins)

        for row in data:
            cv_val = row[1]
            sigma = row[1 + n_cv]
            height = row[1 + 2 * n_cv]
            fes -= height * np.exp(-0.5 * ((grid - cv_val) / sigma) ** 2)

        # Find local minima
        for i in range(1, n_bins - 1):
            if fes[i] < fes[i - 1] and fes[i] < fes[i + 1]:
                minima.append({"cv_values": [float(grid[i])], "energy": float(fes[i])})

        minima.sort(key=lambda x: x["energy"])

    elif n_cv == 2:
        cv1_min, cv1_max = cv_data[:, 0].min(), cv_data[:, 0].max()
        cv2_min, cv2_max = cv_data[:, 1].min(), cv_data[:, 1].max()
        g1 = np.linspace(cv1_min, cv1_max, n_bins)
        g2 = np.linspace(cv2_min, cv2_max, n_bins)
        G1, G2 = np.meshgrid(g1, g2)
        fes = np.zeros_like(G1)

        for row in data:
            cv1, cv2 = row[1], row[2]
            s1, s2 = row[1 + n_cv], row[2 + n_cv]
            h = row[1 + 2 * n_cv]
            fes -= h * np.exp(
                -0.5 * ((G1 - cv1) / s1) ** 2 - 0.5 * ((G2 - cv2) / s2) ** 2
            )

        # Find local minima on 2D grid
        for i in range(1, n_bins - 1):
            for j in range(1, n_bins - 1):
                val = fes[i, j]
                if (
                    val < fes[i - 1, j]
                    and val < fes[i + 1, j]
                    and val < fes[i, j - 1]
                    and val < fes[i, j + 1]
                ):
                    minima.append(
                        {
                            "cv_values": [float(G1[i, j]), float(G2[i, j])],
                            "energy": float(val),
                        }
                    )

        minima.sort(key=lambda x: x["energy"])

    return minima[:n_minima]
